Repository CA-G12/doggie-pics, pull requests merged in 2022-08, with the labels that each got.

#6 File structure
  .eslintrc.json
  .gitignore
  package.json
  public/dom.js
  public/index.html
  public/style.css
  src/logic.js
  src/router.js
  src/server.js
  tests/test.js
Labels: done

#7 adding the html and css of the page header
  public/index.html
  public/style.css
Labels: approved

#8 create and style the searchbar
  public/index.html
  public/style.css
Labels: awaiting review

#9 Create images section
  .gitignore
  public/index.html
  public/style.css
Labels: approved

#16 13 handle search bar
  public/dom.js
  public/fetch.js
  public/index.html
  public/style.css
Labels: approved

#17 adding the router file
  src/router.js
Labels: awaiting review

#18 add the server
  src/server.js
Labels: awaiting review

#21 edits for deploying
  procfile
  src/router.js
  src/server.js
Labels: approved

#23 added fetching pictures into the page
  public/dom.js
Labels: awaiting review

#25 simple edits
  public/dom.js
  public/index.html
  public/logic.js
  src/breeds.json
Labels: approved

#28 27 adding tests and handlers
  handlers/indexHandler.js
  handlers/jsonHandler.js
  src/router.js
  tests/test.js
Labels: awaiting review

#31 added start command
  package.json
Labels: bug, awaiting review

#30 wrote readme file
  README.md
Labels: documentation

#32 added html routing
  src/router.js
Labels: bug, awaiting review
